### ISSUE TITLE
Rebuilding with new 1.13 numpy

### ISSUE THREAD

**Issue by bsipocz** [conda-forge/reproject-feedstock#3]
Could someone with push rights restart the builds to get the one for numpy 1.13 out?

**Comment by cdeil** [comment]
@astrofrog - Could you please trigger the conda reproject build for numpy 1.13?

This missing package is causing problems for our Gammapy CI:
https://github.com/gammapy/gammapy/issues/1066

**Comment by astrofrog** [comment]
I don't think it's just a matter of restarting the builds - the feedstock needs to be re-rendered. I can open a PR.

**Comment by cdeil** [comment]
@astrofrog - Thanks!

**Comment by cdeil** [comment]
@astrofrog - I think you did this in #4 ? Close issue?
